### ISSUE TITLE
Very dark background color on canvas

### ISSUE THREAD

**Issue by javiavid** [code-of-chaos/obsidian-colored_tags_wrangler#14]
The color on canvas when you have light mode is not correct.

CANVAS
Config
<img width="441" alt="image" src="https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/7627504/41f4c052-641f-4d5f-bb6e-7f4260cd5d37">

Light
<img width="271" alt="image" src="https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/7627504/10a335ce-a679-4cb7-83fa-ac6748ab87f1">

Dark
<img width="294" alt="image" src="https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/7627504/ccfac5fb-1573-4c0a-96e8-289859038d29">

KANBAN
Light
<img width="211" alt="image" src="https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/7627504/0a07c664-03c6-4136-ad6a-015d83f924ff">

Dark
<img width="213" alt="image" src="https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/7627504/2c417a1d-142c-4fe1-a4fa-74a274add1ff">

**Comment by AnnaSasDev** [comment]
Ah, I'm sorry I didn't catch this sooner in development.
I work almost exclusively in darkmode and hadn't thought about the ramifications on lightmode .
Will fix ASAP

**Comment by AnnaSasDev** [comment]
I think the main issue is that I made the "background" color for almost everything to be a change in opacity... going forward I might have to revise this

**Comment by AnnaSasDev** [comment]
In the fix that I made, I've removed the opacity system all together, and replaced it with an (HSL) Luminance offset system for extra integrations like Kanban Lists and Cards, Canvas items and Folder Notes. This should fix the issue of the colors of the tag not matching the color of the given field.

Like the toggle to enable separated backgrounds, there is now a toggle to view the luminance offset for a given tag. This value ranges from -0.5 to 0.5 and is applied differently in darkmode vs lightmode.

In Darkmode this turns the backgrounds darker,
Example: luminance offset value of `0.5` will result in a darker color 
Example: luminance offset value of `-0.5` will result in a brighter color 

In Lightmode it turns them brighter.
Example: luminance offset value of `0.5` will result in a brighter color 
Example: luminance offset value of `-0.5` will result in a darker color 

This modifier only applies to kanban cards/lists, Canvas card and Folder Note system

---
### Light Mode: 
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/3091a494-6584-42fe-a3ec-9670601434ad)
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/b6d703dd-10ea-4b90-8c54-6013938eb24f)
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/15c60e38-4acb-4d98-ba0c-dd0ff41addd4)
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/30e3186f-db2e-48c1-9836-87fb7031286a)

---
### Dark Mode: 
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/10081d5e-2c93-4ded-9bcc-ee5e09c82679)
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/11b21ee7-2cab-401d-a85b-7665fbe3e00a)
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/0274340d-ba83-4619-8663-1793179a11f3)
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/0fb54d78-4b6e-4f7e-a197-a7a2508f11e7)

(The red is very over powering in the default example haha)

**Comment by AnnaSasDev** [comment]
This is can be disabled through a setting

**Comment by AnnaSasDev** [comment]
New settings have been added to tweak this by the user

![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/9fa1628b-02f7-4e34-87ba-8e6f12f69b0a)

**Comment by javiavid** [comment]
Thanks!
