### ISSUE TITLE
Enhancement: In an Obsidian Canvas, if you zoom out the colors dissapear

### ISSUE THREAD

**Issue by AnnaSasDev** [code-of-chaos/obsidian-colored_tags_wrangler#18]
zoomed in:
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/38b07c6c-7316-4401-9775-904019b28798)

zoomed out:
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/11efb7c7-5e93-45ae-aea4-33338bb1169b)

expected behavior should be that the colors of the cards remain.

**Comment by AnnaSasDev** [comment]
This can be negated by changing the zoom cut-off level to a higher value, but I think this shouldn't be a workaround.

**Comment by feedhopper** [comment]
I guess this is just normal canvas behaviour. It is meant to save resources. At least that's what I assume

**Comment by AnnaSasDev** [comment]
Oh yeah it is normal behavior's as it stops rendering the md content. Yet i want to look into the possibility of applying the color to the cards, like what happens when you apply a color manually for each canvas card.

**Comment by AnnaSasDev** [comment]
Although #40 adds the requested functionality. I'm leaving this issue open because of the following reason:
- [x] When tag is changed in a card, the color isn't automatically updated, and requires a refresh of the Canvas Leaf.

**Comment by AnnaSasDev** [comment]
Functionally implemented in the available betas for `v1.0.0`
