### ISSUE TITLE
Tag colors for ordinary notes

### ISSUE THREAD

**Issue by feedhopper** [code-of-chaos/obsidian-colored_tags_wrangler#19]
This is a GREAT plugin. I use it for both Kanban and Canvas.

Is there a chance to also extend this functionality to normal notes?
I would very much like to be able to create notes from Kanban and have them in the same colour like on Kanban.

**Comment by AnnaSasDev** [comment]
What exactly do you mean by "extending the functionality to normal notes"?
As in the note background color? Or something else?

**Comment by feedhopper** [comment]
Yes, exactly: Coloring the notes background based on the tags.

The cool thing would be to create notes from Kanban or Canvas and have the same coloring applied on the note when viewing in in editor (read/ edit).

**Comment by AnnaSasDev** [comment]
Sorry it took so long @feedhopper , have been having a lot of health issues lately
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/77fbc15f-b771-4399-b9a9-6ead2406dbb6)
Are you looking for something like this? (needs more tweaking haha)

**Comment by AnnaSasDev** [comment]
will be added with PR #28

**Comment by AnnaSasDev** [comment]
This needs a color mixing update, just like everything else
