### ISSUE TITLE
Tag color for properties

### ISSUE THREAD

**Issue by feedhopper** [code-of-chaos/obsidian-colored_tags_wrangler#20]
It would also be great to extend coloring to other properties.

As far I understand, currently, it is not possible to color individual values within properties such as:
**customproperty1**: _value1_, _value2_, _value3_

But I think it should be possible to individually color
**customproperty1**
**customproperty2**

Maybe the new properties update devs are working on will enhance the addressing of individual propertiy values.

**Comment by AnnaSasDev** [comment]
Hey there, thanks for the enhancement idea!
I already had this in mind myself, but currently it isn't easy to select these tags through CSS (as I've done with all the other elements)

In the example (of my own vault below), these tags should have colors applied to them as I have defined them in the settings.
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/a0bbee0a-abc9-4daf-afbc-06009182014b)

Yet when I look at the DOM through `ctrl+shift+i` they don't look the same as regular `#tags` do in notes. Their 'tagname' is stored as a plain text in a span element, which as far as I'm aware of isn't possible to select through CSS
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/8e6b297c-7621-4ea2-a1ad-72490d71432b)

This doesn't mean I'm not willing to do this. I'm just still wondering how to approach this issue

**Comment by BillyCottrell** [comment]
@AndreasSas if you are limited to CSS its not possible I'm afraid. Thanks to CSS no longer having support for queries with access to content.

It should be possible with jQuery but I don't know if you can use it?
I believe Obsidian doesn't use jQuery don't know if they would allow it...
But if you can, you could create CSS like this:
```css
div[data-property-key="tags"] span:contains("project") {
  background-color: your-desired-color;
}
```

If jQuery is not an option is it possible to alter the HTML itself?
Maybe you could add some extra attributes/classes and use those for the CSS?

Just an idea, hope it helps!

**Comment by feedhopper** [comment]
@AndreasSas Thanks for picking this up. I vaguely remember a conversation on Discord where somebody mentioned difficulties addressing properties properly. Maybe it's best to see whaat will change after next release, apparently the properties improvements are on the immediate roadmap.

**Comment by AnnaSasDev** [comment]
Yeah, they are, if I remember correctly.
For now, I'll not focus as much time on this issue and #19 as they both involve the properties. 
Though I might pick this up as a "free time" thing and work on it slowly. 

Both of these issues are good enhancements and are worth implementing

**Comment by AnnaSasDev** [comment]
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/c0ed13ff-94c6-4544-b04f-513be242fe31)
Have been able to get this to work partially

**Comment by AnnaSasDev** [comment]
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/6ed02f26-1b55-457c-babe-93e3ad69ffdf)
The stroke of the "cross" icon can also easily be affected
