### ISSUE TITLE
tag colors in dataview tables?

### ISSUE THREAD

**Issue by TechnoMaverick** [code-of-chaos/obsidian-colored_tags_wrangler#24]
Hello! First of all, thank you very much for the plugin, I've been wanting a feature like this for a while.

Secondly, and this might not be possible, but I thought I'd ask if it was, to have the tags in a dataview reading view be colored with the plugin. I use properties to insert tags into my notes, so I don't get to often see the colors unless it's on my kanban board. If it's not possible, I might actually swap to not using properties for it, haha.

I use the Minimal theme and the "cards" arrangement for them, if it matters.

(also if there's another way to accomplish this, please let me know! thank you!)

**Comment by AnnaSasDev** [comment]
I haven't had a lot of experience with dataview myself, but I'll look into it.
If you could give me a small working example of the dataview plugin, then I have something to start off with?

(btw, I am planning on making the tags in the properties also have the colors applied to them #20 but I haven't found a good way on how to select them, CSS wise)

**Comment by TechnoMaverick** [comment]
So first I wanted to drop [a thread](https://forum.obsidian.md/t/css-for-different-tags-in-properties/67358) from the official forums on the subject, I'm not sure if it also matters to dataview, but it might be helpful?

Here's a screenshot of ultimately what the dataview table looks like:
![Obsidian_o6iypfTIiR](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/118154253/5777550c-0b3c-40c6-bf39-596353a02c3d)

![Obsidian_KretHNgx6R](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/118154253/cab66ef0-a051-4bb7-a376-c5a966f3e2b5)
The actual query (I believe it's called?) in the table. the #testingtags part is how I'm telling it to pull the notes, but the "tags" part is how it's actually listing the above final product. That's the part I was wondering if it could be color tagged.

![Obsidian_0mfDZptfSs](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/118154253/0f84a8af-b7c4-497c-ab2f-cf64c21b9362)
And then I'm pretty sure you don't need this, but the tag in properties.

I really appreciate you looking into it! Let me know if I can help with any more screenshots or anything, sadly I don't know how to code.

**Comment by AnnaSasDev** [comment]
Hey @TechnoMaverick with the following dataview code block:
```dataview
list
tags from #folder-section 
```

I got the following output list:
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/4eadd396-771c-48ed-884c-a227529f409f)
The tags aren't really presented as tags and are thus not really that simple to identify ... I don't know how I could approach this issue

**Comment by TechnoMaverick** [comment]
No problem at all! I just thought it was worth asking about, I had no idea how it works. Very much still appreciate the plugin and you working on it.

**Comment by nbycoder** [comment]
Hi I'm super late here but if you use file.tags or file.etags they show coloured :)
