### ISSUE TITLE
Background color doesn't change based on color of tag

### ISSUE THREAD

**Issue by ubiqn52** [code-of-chaos/obsidian-colored_tags_wrangler#38]
When I create a new colored tag in settings, the background color is initialized at #646464 but doesn't update when I change the main color of the tag. However, the colors of the tags I had before the most recent update did automatically update.

**Comment by AnnaSasDev** [comment]
Sorry for the late reply
This feature was up for a rework, but was accidentally removed.
It is currently reimplemented (in the 0.17.1 update) slightly differently. The Setting "Enable button for Auto Background coloring" will make a button appear next to each tag setting, allowing you to press this manually for an auto generated background color.
See image below:
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/8ef04497-4612-48f2-9e8b-66737011db3a)

**Comment by AnnaSasDev** [comment]
Does this solve the issue for you @Pellucid1137  ?

**Comment by ubiqn52** [comment]
Works really well now, thanks for the effort :)
