### ISSUE TITLE
Not working since last update (Lowercase tags only)

### ISSUE THREAD

**Issue by monkeyscalper** [code-of-chaos/obsidian-colored_tags_wrangler#44]
**Describe the bug**
The plugin has completely stopped working since the last update

**Versions (please complete the following information):**
- Obsidian Version : 1.5.3
- Plugin Version : 0.19.0

**To Reproduce**
Steps to reproduce the behavior: I created a new vault with only this plugin, set a color for a tag but it doesn't reflect the changes in the note. 

**Expected behavior**
It was working fine for me up to version 0.19.0. This plugin updated at the same time as others so I wondered if a conflict caused this, but given it doesn't work in a new vault with just this plugin, I believe something in the last update has caused it to stop working.

**Comment by AnnaSasDev** [comment]
Unfortunately can't reproduce this myself... 
Installed it from the community plugins to a new vault (on desktop, windows) as well, and is behaving like expected.
Are you using obsidian on Desktop / windows as well? (will update the bug report template so I don't have to ask this in the future haha)
Something that could have gone wrong (though I try and test this thoroughly) is that a data.json's version update went wrong on a migration from one version to another.

**Comment by monkeyscalper** [comment]
I'm on MacOS but given it is working for you I thought I'd give it another try. It still wasn't working but then noticed if I type the tag in all lower case it does work. So despite my tags all starting with uppercase letter and matching this in the settings (this has been working fine previosly), it will now only change the colour if I use all lowercase letters. 
<img width="708" alt="image" src="https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/7281414/4014afb3-3fc5-4764-8700-1bfae6d8775d">

**Comment by AnnaSasDev** [comment]
That is strange behavior indeed.
I'll look into it, and fix asap.

**Comment by AnnaSasDev** [comment]
This should now be fixed in version `0.19.1`

**Comment by monkeyscalper** [comment]
Awesome, thanks for fixing it so quick! Great little plugin has changed the way I journal so really appreciate it.
