### ISSUE TITLE
Can't install or update latest release of plugin

### ISSUE THREAD

**Issue by evanharmon1** [code-of-chaos/obsidian-colored_tags_wrangler#47]
**Describe the bug**
Obsidian gives an error popup whenever I try to update or install the plugin. I have tried on a fresh vault as well.

**Versions (please complete the following information):**
- Obsidian Version : ...
- Obsidian Platfrom : 
  - [ ] Windows
  - [ ] Mobile Android
  - [ ] Mobile iOS
  - [x] MacOS
  - [ ] Linux

- Plugin Version : ...
0.19.0
(I think I was on this version when I couldn't update. But I can't install or update from a new vault)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dolores824** [comment]
Same here in win11 (version 1.5.3, with installer 1.4.13)
Tried to update or install in the plugin community, with `Error: Request failed, status 404` in console
Then tried to use BRAT to download, with `BRAT: code-of-chaos/obsidian-colored_tags_wrangler
The release is not complete and cannot be download. main.js is missing from the Release`

**Comment by AnnaSasDev** [comment]
Apparently I had forgotten to set the draft of version `0.19.2` to release.
I was now able to install the 0.19.2 update, so I'm closing this issue
I'm sorry for the inconvenience
