### ISSUE TITLE
Apply color to nested tags

### ISSUE THREAD

**Issue by aikruger** [code-of-chaos/obsidian-colored_tags_wrangler#54]
the color applied to the tag disappears if you add nested tags to the original tag. additionally if I create a tag #_/ it only colors the first part and not the whole of the tag

**Describe the solution you'd like**
same color applies to tag regardless of nested terms

**Comment by PanManOnTheXan** [comment]
It would also be useful to be able to set custom colors for each nested tag

**Comment by AnnaSasDev** [comment]
> It would also be useful to be able to set custom colors for each nested tag

The current idea is, if you enable this specific setting, to have each nested tag be a gradient offset of the main color. But I'm very much still in the plnanning phase of this.

**Comment by PanManOnTheXan** [comment]
> > It would also be useful to be able to set custom colors for each nested tag
> 
> The current idea is, if you enable this specific setting, to have each nested tag be a gradient offset of the main color. But I'm very much still in the plnanning phase of this.

That sounds really cool, it's a feature I am really looking forward to, since my vault is basically only using nested tags. As long as they'll render I am happy. Good luck working on it!

**Comment by AnnaSasDev** [comment]
> > > It would also be useful to be able to set custom colors for each nested tag
> > 
> > 
> > The current idea is, if you enable this specific setting, to have each nested tag be a gradient offset of the main color. But I'm very much still in the plnanning phase of this.
> 
> That sounds really cool, it's a feature I am really looking forward to, since my vault is basically only using nested tags. As long as they'll render I am happy. Good luck working on it!

As a side note, in the current version `0.19.3` nested tags are already "supported", but you have to define them yourself in the tag field. For example: 

![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/e070ff42-ac4e-4860-8093-57ae860e6221)

I know this is super tedious, and given the size of some people's vaults not always managable (this is why I really want to implement this in the `1.0.0` version as an automated thing). Just make sure to delimit each tag with a `;` and/or a new-line.

**Comment by AnnaSasDev** [comment]
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/955c083a-ca18-4a0e-a998-2c4f9cd1023d)
![image](https://github.com/code-of-chaos/obsidian-colored_tags_wrangler/assets/74367457/426eb318-4829-47ed-a595-67675a9743e4)

Hey in the new beta for `1.0.0-BETA-002`, available to you by using BRAT it is now finally possible to assign nested tags. Mind you this is still in very early beta.

**Comment by AnnaSasDev** [comment]
Is functionally implemented in the available betas for `v1.0.0`
