### ISSUE TITLE
This plugin doesn't work properly when the tag has an underscore _ character

### ISSUE THREAD

**Issue by jiestebanw** [code-of-chaos/obsidian-colored_tags_wrangler#82]
**Describe the bug**
If the tag has an underscore _ character, then it is not properly colored

**Versions (please complete the following information):**

- Obsidian Version : 1.6.7
- Obsidian Platfrom :
	- [x] Windows
	- [ ] Mobile Android
	- [ ] Mobile iOS
	- [ ] MacOS
	- [ ] Linux

- Plugin Version : 0.19.3

**To Reproduce**
Use this plugin with a tag that has an underscore _ character, 

**Expected behavior**
Tag should be colored according to the configuration

**Screenshots**
Attached here
![image](https://github.com/user-attachments/assets/e0cf959b-86f9-4ef1-8fb7-cf5d135bcdc8)
the 3 tags #n/CPM, #n/GBD_DELNO and #n/AGX has the same color configuration 
Nevertheless since #n/GBD_DELNO has an underscore _ in its name, it is not properly colored

**Additional context**

**Comment by AnnaSasDev** [comment]
![image](https://github.com/user-attachments/assets/2e69d17b-c115-47db-85cc-e3ba22a5d0e2)
Currently working on the master branch (which is in current preview of 1.0.0) , though there is still an issue with it "blinking" in out of existence on file edit.
I'll mark this issue as resolved as it will be added to 1.0.0
